language: go

matrix:
  include:
    - go: 1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autoconf libdevmapper-dev libsqlite3-dev -qq
  - cd `mktemp -d`
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz
  - tar xJf autoconf-2.69.tar.xz
  - cd autoconf-2.69
  - ./configure && make && sudo make install
  - wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz
  - tar xJf automake-1.15.tar.xz
  - cd automake-1.15
  - ./configure && make && sudo make install
  - mkdir -p ${GOPATH}/src/github.com/hyperhq
  - git clone https://github.com/hyperhq/runv.git ${GOPATH}/src/github.com/hyperhq/runv
  - wget https://git.fedorahosted.org/cgit/lvm2.git/snapshot/lvm2-2_02_131.tar.xz
  - tar xf lvm2-2_02_131.tar.xz
  - cd lvm2-2_02_131
  - ./configure && make device-mapper && sudo make install

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - ./verify-gofmt.sh
  - ./autogen.sh
  - ./configure 
  - make

